language: python
python:
- '3.6'
- '3.7'
install:
- pip install --upgrade  coverage pytest pytest-cov codecov
- python setup.py install
script:
- python -m pytest -vv --cov=betagen/
deploy:
  provider: pypi
  user: __token__
  password:
    secure: Nzxl9Uhj6foTi1PSu1VX6zjU95RVeWPjo4ODhRUiZ5GjEBGbK8IDGqDbq5qiZk/J2a092gjqgt1e+sXlHsY7jJcNq0ZOe6F2ITabIdv7xGA5q8jnkuymWam0IVuNUMneDVUvU9uswQ+FpPFYWpfpgqfOm8Z/Aqvm27ky4DPxvFwoBPIHzJKCZtkx7lW60MWmabVaPbJUIiuPEANc+GYYEGs8+mqu2oVc/8BlIzROeYJ2NqDZCH+ymCSi3XnYy8j7i8YDs5lWzf5waDUpjRwIW4TbTgXMoufL6qceTlyhDFz4+oSU5byzzVjZ4Ntscz4m0s6LBqnzW3sEF+apSJJg72Nd3uy3kHdUTpYqEywD6Z9bG4opYPoknEdbj7VZJ5KwGqY9nrDwQA66+0+mg4vAIvWBQmaFONMWDhviLqd6QNnY34pny1ZkJNPEaUohxIEowByxfOgiRwNUkuAPSVMKv30LrT2jUorPFsYVCveGPg1Qwe3F3/uOfT2IOC20Pcwf7X1bFyEBQWfQkQOn9N/EIIfiNQHaTMiXnFeihdHjSumSRN1GAb3+d1T8gXB91ND4HA8igs+LcfIajCFAS4M3t8/MCCqbLJTTHCok4NDA8Mof/4GpUsbyTGjKqr2FBj9cSlh44laIkynHQLHkizUIwX5Jp6AeHuUDKSYvzW9pFRw=
  on:
    tags: true
  distributions: sdist bdist_wheel
  skip_existing: true
