language: python
python:
- '3.6'
- '3.7'
install:
- pip install --upgrade  coverage pytest pytest-cov codecov
- python setup.py install
script:
- python -m pytest -vv --cov=betagen/
deploy:
  provider: pypi
  user: "__token__"
  password:
    secure: wXvtyECCCaddloV+KzIHLO3Gp935Cb3wY88aexrNiNSp9MO8Vvdr5i2Mb9regQmsphdR/F5eXMx4p/vD5DnpspcERRshFqORytUVgJlLs+3I3uDPgEr6n8jqFGJTlmtzYlkSxriCUhhaxUBXy/XOs9zMmgU6+C6V8bH6ilA4yxRqh7w6ToS8sWKKQpJJ3KjMjkyZCl8F+TS/eqiQq7YFwPY0fyhHyfbcR6xFYGnAG4lMK5E7tVlBZlo6BrMACLR2uOB3CLUkYKXrZmI5pnk/fv1XJxMNccV5l0Xfsvapw5Dv76ilVq5M45YOQUNazUsgk0NYChl95OGQBlRb4tFo4+D28/Yxzh3A4DYMz4kH/9akv5ARtxaZj2azMxB4bFsjsseUDFAc+0/RCQNbQ12qdh6BSa7/yuT1TpET7PRjCtBV/h6wMMlJGygWAwBKPs+K2J7euIRPSv2vCEN7s2D3TGR+XQNgaxVhzQ+JZeyb75sYa6mT0rvjJrpg1q9C6cup9KWY8YoKVJmsGXSE+ok8UZ3A01aNFcL/ErzKTpTgwJ90RscMxhQqAaO0y8EuUEZip71Od9Y4q27K22USa7ayoDuuKMLgwv2RoIzHyY+hxUUsRKPx7zpeHTGH+Kz9Z4CShcp9FPxZHAcWRfVreYng+3teFq+yFVaS1lm6GChvC14=

  on:
    tags: true
  distributions: "sdist bdist_wheel"
  skip_existing: true
