language: python
python:
- '3.6'
- '3.7'
install:
- pip install --upgrade  coverage pytest pytest-cov codecov
- python setup.py install
script:
- python -m pytest -vv --cov=betagen/
deploy:
  provider: pypi
  user: "__token__"
  on:
    tags: true
  distributions: sdist bdist_wheel
  skip_existing: true
  password:
    secure: f96+Y9VSLLXLlCMh1rTZ8sjcrLtKTAgQg7y+qjwzF25hqm/HgA4U7ZInj1vRpNdwDGAVps6fZkuaaQW5K9ZGo8OUH+FIRhjh/e84UZhTnMYKW/c3+MUNUVVTFAIoCH63UEEHuM6vB8EoKCDthm5ai8EmhNP+iNMVVkGyRS/eX2iKJe+3ZftR0/dSz3luN08QNbmztfUUwwMg8Wsjj4H4Ns4LkLlrURxTD3KuadMs32SPTW30AdIrzo1S74QSOWuvQdC3YeUgEEOu3IzjqlW1r/+jWLexrswwDGVl1Wx9ZNGqzcHLDVzd8OHXrjXfSkEyg601mMcbsJt+C4uu2SNH6gRayMTVRK9c0/doJ27gTIBBCqptorhD8cBhdF7yFS/tK8E4zfRePHv419hVHEXAjDJBX0rYablviFVVKzi4DHQjOw3loKTo6tdLQQregPqAMI7yROxyjFevoXDl60EypD6LBigAivKsfP4XVPk/NR1aekrZCnF3uVrJM4Al+QpcPMr1yvGVGbypRAEUPB42jcaV84Qxia+ET5Isiqkz+BLke80xekSJub1SAIHU3PfaWDSeJYRBKD3k61yMcTNm6P73oj3u0CqlP9wMS7FS5XSxHMic/FWxR3yHsrKkjDH48k2umO+MyCRu0itSe3Jq10VecoRvhNjNETx6qbT/6Ko=
