language: python
python:
- '3.6'
- '3.7'
install:
- pip install --upgrade  coverage pytest pytest-cov codecov
- python setup.py install
script:
- python -m pytest -vv --cov=betagen/
deploy:
  provider: pypi
  user: __token__
  password:
    secure: vRFg8614LKieLP0vnU/nVslFUaFPvJA1FQTG7nerWZk9SFgC1QmDWs4tGA1OmEC6Qb3zMPh0sboh5NycepPyYAfZQjLg9bIv9gZITuxEUiJ0217ocBOHi9rqOnBy8LA2x2toHCwOCkKla+jkoqOj3P6GQ0CkZbzF02DKdIy2w4NI7bcvVD/ZsR8NbrmiduAH0EFECZm/zPqgGJAraCLkDwvJ1J5U+djlP0NgauDV+foFolJylZPkBxdjLhFmVCXfbqZbGu/2Ik32YsnKnavCw0++CxwWHh9hevwZUqPKN0x1vfPFwuxLXG4ToQ5icyHuZkLUSF0WfterJtVSl5QjdYui7kh5m6LgV8QmCFYr3gD3+eaSFfmD1MdRyRxsmBMKHSuAxrm/HQptWm20NBBeFNQnGZcMTn2oBegWrYPlYbFezRzt6MZby8Uo820M6qG/pzidjgW+/aexTtdDSM7XnXfb8Iub3mStkIt+RwOsc3M6wsnWJQ01HVjLzgI2lSqlxTy2hHuCjkWp5WGB7cZg8rPsd0gy5BWHdXE1UDHYwHYiiOsnK08NoKBCTWO6aUtfJ0V+nsgw7amHfs8eSJUT7jum7wHUusW8UV8PZc235pNylhEjHO8lv0pNPqwW7W1QDY/YgdJIFNUpHrvR/51nzBSvOOVilVofFydZJHbAwvA=

  on:
    tags: true
  distributions: sdist bdist_wheel
  skip_existing: true
 
