language: python
python:
- '3.6'
- '3.7'
install:
- pip install --upgrade numpy  coverage pytest pytest-cov cython codecov
- python setup.py install
script:
- python -m pytest -vv --cov=rainbowpy/
deploy:
  provider: pypi
  user: "__token__"
  password:
    secure: gudmkz9t0eWAZveYbBiJIaY0EP4Ara64RFIAx7iMAJZY8FmgRdUfYtD+zX3BJw5q+75xuwjKUlyUyjSzeRIH+fbpN5WJV/qpl9AKAhZJg7CKstEG3EA168eaFVZrAK6C4PRBL3W7Ut6TFOy0PeoTlVc774YvH+I4TJBtT0y2mXsgfyUlF1AXzd94Ta0vv7qlqeMpafLpBJeE/1XxbtS0USxoqO5fb64VqNg+1hJr54wd2LhZIUpHywJW4j7uMiPCpBV/N+XZMc5iwS4SjkOluxtqpwuRshpKRGRnC4zCkRT48YIVDRIamOcm6UDErGrsgOUK9qJqT4flK+kBTTowgbyWm6Wl7pZKbvsNi6SquRflzLrEDaed2v0OeZ5g+ZY682i1r9i/st9yW903Mv1Ne+k9nRJNGxcLImz4zMvf1kY2AYiTQSon8yszQTUQ77bal531NBxbvz7OVUwlkQ6Jv7ZS3EwTVlOKC7hZKhajf+5TlHomLrQoDx1slF0iv4altwLgJeN1WPcRalpZSX3U/z4jk0tJfhq6WMOOHxoMUTKN7TsAeKv6wEiiZX06v6wY1MqPyiobtUDuT1nlwngMI9Du98pnVNkZ1rjGfd+Ufi4RsEErDqkgt1twl5tE8/Cu12bGx507s0yEmhgfjgzO46oGomL3Cy1ihz5HXT2dIdI=
  on:
    tags: true
  distributions: "sdist bdist_wheel" # Your distributions here
  skip_existing: true
